version: '3.7'

networks:
    app-network:
        driver: bridge

services:
    database:
        container_name: database
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST=youtube_mashup_database
            - POSTGRES_PORT=5433
            - POSTGRES_DB=youtube-mashup-dev
        ports:
            - "5432:5432"
        networks:
            - app-network
    frontend:
        container_name: frontend
        build:
            context: ./client
            dockerfile: Dockerfile
        command: bash -c "yarn start"
        restart: always
        volumes:
            - ./client:/frontend
        ports:
            - "8080:8080"
        expose:
            - "8080"
        environment:
            - NODE_ENV=development
        networks:
            - app-network
        depends_on:
            - backend
    backend:
        container_name: backend
        build:
            context: ./server
            dockerfile: Dockerfile
        command: bash -c "yarn run db:migrate && yarn run seed:all && yarn start"
        restart: always
        volumes: 
            - ./server:/server
        ports:
            - "8081:8081"
        expose:
            - "8081"
        env_file:
            - ./server/src/config/env
        networks:
            - app-network
        depends_on:
            - database
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
        networks:
            - app-network
        volumes:
            - ./nginx/:/etc/nginx/conf.d/
        depends_on:
            - frontend
            - backend
