version: '3.7'

services:
    youtube_clipper_database:
        container_name: youtube_clipper_database
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST=youtube_clipper_database
            - POSTGRES_PORT=5432
            - POSTGRES_DB=youtube-clipper-dev
        ports:
            - "5432:5432"
