module.exports = {
    channels: [
        { name: 'land', background: 'https://i.ytimg.com/vi/shTUk4WNWVU/maxresdefault.jpg', userId: 1, createdAt: new Date(), updatedAt: new Date() },
        { name: 'sea', background: 'https://upload.wikimedia.org/wikipedia/commons/5/53/GabrielMedina-001.jpg', userId: 1, createdAt: new Date(), updatedAt: new Date() },
        { name: 'air', background: 'https://i.ytimg.com/vi/apYEQlGlUAY/maxresdefault.jpg', userId: 1, createdAt: new Date(), updatedAt: new Date() },
        { name: 'land', background: 'https://i.ytimg.com/vi/shTUk4WNWVU/maxresdefault.jpg', userId: 2, createdAt: new Date(), updatedAt: new Date() },
        { name: 'sea', background: 'https://upload.wikimedia.org/wikipedia/commons/5/53/GabrielMedina-001.jpg', userId: 2, createdAt: new Date(), updatedAt: new Date() },
        { name: 'air', background: 'https://i.ytimg.com/vi/apYEQlGlUAY/maxresdefault.jpg', userId: 2, createdAt: new Date(), updatedAt: new Date() },
        { name: 'land', background: 'https://i.ytimg.com/vi/shTUk4WNWVU/maxresdefault.jpg', userId: 3, createdAt: new Date(), updatedAt: new Date() },
        { name: 'sea', background: 'https://upload.wikimedia.org/wikipedia/commons/5/53/GabrielMedina-001.jpg', userId: 3, createdAt: new Date(), updatedAt: new Date() },
        { name: 'air', background: 'https://i.ytimg.com/vi/apYEQlGlUAY/maxresdefault.jpg', userId: 3, createdAt: new Date(), updatedAt: new Date() },
        { name: 'land', background: 'https://i.ytimg.com/vi/shTUk4WNWVU/maxresdefault.jpg', userId: 4, createdAt: new Date(), updatedAt: new Date() },
        { name: 'sea', background: 'https://upload.wikimedia.org/wikipedia/commons/5/53/GabrielMedina-001.jpg', userId: 4, createdAt: new Date(), updatedAt: new Date() },
        { name: 'air', background: 'https://i.ytimg.com/vi/apYEQlGlUAY/maxresdefault.jpg', userId: 4, createdAt: new Date(), updatedAt: new Date() },
        { name: 'land', background: 'https://i.ytimg.com/vi/shTUk4WNWVU/maxresdefault.jpg', userId: 5, createdAt: new Date(), updatedAt: new Date() },
        { name: 'sea', background: 'https://upload.wikimedia.org/wikipedia/commons/5/53/GabrielMedina-001.jpg', userId: 5, createdAt: new Date(), updatedAt: new Date() },
        { name: 'air', background: 'https://i.ytimg.com/vi/apYEQlGlUAY/maxresdefault.jpg', userId: 5, createdAt: new Date(), updatedAt: new Date() },
    ],
    users: [
        { authId: '1', displayName: 'joe cool', firstName: 'Joe', lastName: 'Cool', email: 'joe_cool@gmail.com', createdAt: new Date(), updatedAt: new Date() },
        { authId: '2', displayName: 'jane doe', firstName: 'Jane', lastName: 'Doe', email: 'jane_doe@gmail.com', createdAt: new Date(), updatedAt: new Date() },
        { authId: '3', displayName: 'frank thetank', firstName: 'Frank', lastName: 'TheTank', email: 'frank_thetank@gmail.com', createdAt: new Date(), updatedAt: new Date() },
        { authId: '4', displayName: 'john reese', firstName: 'John', lastName: 'Reese', email: 'john_reese@gmail.com', createdAt: new Date(), updatedAt: new Date() },
        { authId: '5', displayName: 'harold finch', firstName: 'Harold', lastName: 'Finch', email: 'harold_finch@gmail.com', createdAt: new Date(), updatedAt: new Date() },
    ],
    videos: [
        { url: 'OMflBAXJJKc', channelId: 1, createdAt: new Date(), updatedAt: new Date() },
        { url: 'x76VEPXYaI0', channelId: 1, createdAt: new Date(), updatedAt: new Date() },
        { url: 'evj6y2xZCnM', channelId: 1, createdAt: new Date(), updatedAt: new Date() },
        { url: '5XpU5M0ZCKM', channelId: 2, createdAt: new Date(), updatedAt: new Date()},
        { url: '-hfKtUT4ISs', channelId: 2, createdAt: new Date(), updatedAt: new Date() },
        { url: 'JYYsAxC0Dic', channelId: 2, createdAt: new Date(), updatedAt: new Date() },
        { url: 'rbFvzRsDBN4', channelId: 3, createdAt: new Date(), updatedAt: new Date() },
        { url: '-C_jPcUkVrM', channelId: 3, createdAt: new Date(), updatedAt: new Date() },
        { url: 'FHtvDA0W34I', channelId: 3, createdAt: new Date(), updatedAt: new Date() },
    ],
    likes: [
        { startTime: 43, stopTime: 48, videoId: 1, channelId: 1, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 74, stopTime: 82, videoId: 1, channelId: 1, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 38, stopTime: 42, videoId: 2, channelId: 1, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 70, stopTime: 90, videoId: 3, channelId: 1, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 29, stopTime: 52, videoId: 4, channelId: 2, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 80, stopTime: 98, videoId: 4, channelId: 2, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 147, stopTime: 157, videoId: 5, channelId: 2, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 11, stopTime: 34, videoId: 6, channelId: 2, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 20, stopTime: 38, videoId: 7, channelId: 3, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 52, stopTime: 80, videoId: 7, channelId: 3, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 170, stopTime: 194, videoId: 7, channelId: 3, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 95, stopTime: 116, videoId: 8, channelId: 3, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 47, stopTime: 64, videoId: 9, channelId: 3, createdAt: new Date(), updatedAt: new Date() },
    ],
    user_likes: [
        { userId: 1, likeId: 1, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, likeId: 1, createdAt: new Date(), updatedAt: new Date() },
        { userId: 4, likeId: 1, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, likeId: 2, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, likeId: 2, createdAt: new Date(), updatedAt: new Date() },
        { userId: 4, likeId: 2, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, likeId: 3, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, likeId: 3, createdAt: new Date(), updatedAt: new Date() },
        { userId: 4, likeId: 3, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, likeId: 4, createdAt: new Date(), updatedAt: new Date() },
        { userId: 5, likeId: 4, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, likeId: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, likeId: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 4, likeId: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, likeId: 6, createdAt: new Date(), updatedAt: new Date() },
        { userId: 4, likeId: 6, createdAt: new Date(), updatedAt: new Date() },
        { userId: 5, likeId: 6, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, likeId: 7, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, likeId: 7, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, likeId: 8, createdAt: new Date(), updatedAt: new Date() },
        { userId: 4, likeId: 8, createdAt: new Date(), updatedAt: new Date() },
        { userId: 5, likeId: 8, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, likeId: 9, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, likeId: 9, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, likeId: 10, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, likeId: 10, createdAt: new Date(), updatedAt: new Date() },
        { userId: 4, likeId: 10, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, likeId: 11, createdAt: new Date(), updatedAt: new Date() },
        { userId: 5, likeId: 11, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, likeId: 12, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, likeId: 12, createdAt: new Date(), updatedAt: new Date() },
        { userId: 4, likeId: 12, createdAt: new Date(), updatedAt: new Date() },
        { userId: 5, likeId: 12, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, likeId: 13, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, likeId: 13, createdAt: new Date(), updatedAt: new Date() },
        { userId: 4, likeId: 13, createdAt: new Date(), updatedAt: new Date() },
    ]
};
