module.exports = {
    channels: [
        { name: 'land', background: 'https://i.ytimg.com/vi/shTUk4WNWVU/maxresdefault.jpg', userId: 1, createdAt: new Date(), updatedAt: new Date() },
        { name: 'sea', background: 'https://upload.wikimedia.org/wikipedia/commons/5/53/GabrielMedina-001.jpg', userId: 1, createdAt: new Date(), updatedAt: new Date() },
        { name: 'air', background: 'https://i.ytimg.com/vi/apYEQlGlUAY/maxresdefault.jpg', userId: 1, createdAt: new Date(), updatedAt: new Date() },
        { name: 'land', background: 'https://i.ytimg.com/vi/shTUk4WNWVU/maxresdefault.jpg', userId: 2, createdAt: new Date(), updatedAt: new Date() },
        { name: 'sea', background: 'https://upload.wikimedia.org/wikipedia/commons/5/53/GabrielMedina-001.jpg', userId: 2, createdAt: new Date(), updatedAt: new Date() },
        { name: 'air', background: 'https://i.ytimg.com/vi/apYEQlGlUAY/maxresdefault.jpg', userId: 2, createdAt: new Date(), updatedAt: new Date() },
        { name: 'Honest Trailers', background: 'https://i.ytimg.com/vi/shTUk4WNWVU/maxresdefault.jpg', userId: 3, createdAt: new Date(), updatedAt: new Date() },
        { name: 'sea', background: 'https://upload.wikimedia.org/wikipedia/commons/5/53/GabrielMedina-001.jpg', userId: 3, createdAt: new Date(), updatedAt: new Date() },
        { name: 'air', background: 'https://i.ytimg.com/vi/apYEQlGlUAY/maxresdefault.jpg', userId: 3, createdAt: new Date(), updatedAt: new Date() }
    ],
    users: [
        { authId: '1', displayName: 'Harold Finch', firstName: 'Harold', lastName: 'Finch', email: 'harold_finch@gmail.com', createdAt: new Date(), updatedAt: new Date() },
        { authId: '2', displayName: 'John Reese', firstName: 'John', lastName: 'Reese', email: 'john_reese@gmail.com', createdAt: new Date(), updatedAt: new Date() }
    ],
    videos: [
        { url: 'OMflBAXJJKc', channelId: 1, createdAt: new Date(), updatedAt: new Date() },
        { url: 'x76VEPXYaI0', channelId: 1, createdAt: new Date(), updatedAt: new Date() },
        { url: 'evj6y2xZCnM', channelId: 1, createdAt: new Date(), updatedAt: new Date() },
        { url: '5XpU5M0ZCKM', channelId: 2, createdAt: new Date(), updatedAt: new Date()},
        { url: '-hfKtUT4ISs', channelId: 2, createdAt: new Date(), updatedAt: new Date() },
        { url: 'JYYsAxC0Dic', channelId: 2, createdAt: new Date(), updatedAt: new Date() },
        { url: 'rbFvzRsDBN4', channelId: 3, createdAt: new Date(), updatedAt: new Date() },
        { url: '-C_jPcUkVrM', channelId: 3, createdAt: new Date(), updatedAt: new Date() },
        { url: 'FHtvDA0W34I', channelId: 3, createdAt: new Date(), updatedAt: new Date() },
        { url: 'OMflBAXJJKc', channelId: 4, createdAt: new Date(), updatedAt: new Date() },
        { url: 'x76VEPXYaI0', channelId: 4, createdAt: new Date(), updatedAt: new Date() },
        { url: 'evj6y2xZCnM', channelId: 4, createdAt: new Date(), updatedAt: new Date() },
        { url: '5XpU5M0ZCKM', channelId: 5, createdAt: new Date(), updatedAt: new Date()},
        { url: '-hfKtUT4ISs', channelId: 5, createdAt: new Date(), updatedAt: new Date() },
        { url: 'JYYsAxC0Dic', channelId: 5, createdAt: new Date(), updatedAt: new Date() },
        { url: 'rbFvzRsDBN4', channelId: 6, createdAt: new Date(), updatedAt: new Date() },
        { url: '-C_jPcUkVrM', channelId: 6, createdAt: new Date(), updatedAt: new Date() },
        { url: 'FHtvDA0W34I', channelId: 6, createdAt: new Date(), updatedAt: new Date() },
        { url: 'omQNRgzFSFo', channelId: 7, createdAt: new Date(), updatedAt: new Date() },
        { url: 'IOA6G5PhnRM', channelId: 7, createdAt: new Date(), updatedAt: new Date() },
        { url: 'tJAZ35-EO1s', channelId: 7, createdAt: new Date(), updatedAt: new Date() },
        { url: '5XpU5M0ZCKM', channelId: 8, createdAt: new Date(), updatedAt: new Date()},
        { url: '-hfKtUT4ISs', channelId: 8, createdAt: new Date(), updatedAt: new Date() },
        { url: 'JYYsAxC0Dic', channelId: 8, createdAt: new Date(), updatedAt: new Date() },
        { url: 'rbFvzRsDBN4', channelId: 9, createdAt: new Date(), updatedAt: new Date() },
        { url: '-C_jPcUkVrM', channelId: 9, createdAt: new Date(), updatedAt: new Date() },
        { url: 'FHtvDA0W34I', channelId: 9, createdAt: new Date(), updatedAt: new Date() },
    ],
    moments: [
        { startTime: 43, stopTime: 48, videoId: 1, channelId: 1, createdByUser: 1, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 74, stopTime: 82, videoId: 1, channelId: 1, createdByUser: 1, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 38, stopTime: 42, videoId: 2, channelId: 1, createdByUser: 1, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 70, stopTime: 90, videoId: 3, channelId: 1, createdByUser: 1, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 29, stopTime: 52, videoId: 4, channelId: 2, createdByUser: 1, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 80, stopTime: 98, videoId: 4, channelId: 2, createdByUser: 1, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 147, stopTime: 157, videoId: 5, channelId: 2, createdByUser: 1, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 11, stopTime: 34, videoId: 6, channelId: 2, createdByUser: 1, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 20, stopTime: 38, videoId: 7, channelId: 3, createdByUser: 1, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 52, stopTime: 80, videoId: 7, channelId: 3, createdByUser: 1, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 170, stopTime: 194, videoId: 7, channelId: 3, createdByUser: 1, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 95, stopTime: 116, videoId: 8, channelId: 3, createdByUser: 1, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 47, stopTime: 64, videoId: 9, channelId: 3, createdByUser: 1, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 43, stopTime: 48, videoId: 10, channelId: 4, createdByUser: 2, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 74, stopTime: 82, videoId: 10, channelId: 4, createdByUser: 2, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 38, stopTime: 42, videoId: 11, channelId: 4, createdByUser: 2, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 70, stopTime: 90, videoId: 12, channelId: 4, createdByUser: 2, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 29, stopTime: 52, videoId: 13, channelId: 5, createdByUser: 2, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 80, stopTime: 98, videoId: 13, channelId: 5, createdByUser: 2, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 147, stopTime: 157, videoId: 14, channelId: 5, createdByUser: 2, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 11, stopTime: 34, videoId: 15, channelId: 5, createdByUser: 2, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 20, stopTime: 38, videoId: 16, channelId: 6, createdByUser: 2, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 52, stopTime: 80, videoId: 16, channelId: 6, createdByUser: 2, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 170, stopTime: 194, videoId: 16, channelId: 6, createdByUser: 2, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 95, stopTime: 116, videoId: 17, channelId: 6, createdByUser: 2, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 47, stopTime: 64, videoId: 18, channelId: 6, createdByUser: 2, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 43, stopTime: 48, videoId: 19, channelId: 7, createdByUser: 3, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 74, stopTime: 82, videoId: 19, channelId: 7, createdByUser: 3, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 38, stopTime: 42, videoId: 20, channelId: 7, createdByUser: 3, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 70, stopTime: 90, videoId: 21, channelId: 7, createdByUser: 3, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 29, stopTime: 52, videoId: 22, channelId: 8, createdByUser: 3, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 80, stopTime: 98, videoId: 22, channelId: 8, createdByUser: 3, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 147, stopTime: 157, videoId: 23, channelId: 8, createdByUser: 3, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 11, stopTime: 34, videoId: 24, channelId: 8, createdByUser: 3, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 20, stopTime: 38, videoId: 25, channelId: 9, createdByUser: 3, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 52, stopTime: 80, videoId: 25, channelId: 9, createdByUser: 3, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 170, stopTime: 194, videoId: 25, channelId: 9, createdByUser: 3, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 95, stopTime: 116, videoId: 26, channelId: 9, createdByUser: 3, createdAt: new Date(), updatedAt: new Date() },
        { startTime: 47, stopTime: 64, videoId: 27, channelId: 9, createdByUser: 3, createdAt: new Date(), updatedAt: new Date() },
    ],
    user_moments: [
        { userId: 1, momentId: 1, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, momentId: 1, createdAt: new Date(), updatedAt: new Date() },
        { userId: 4, momentId: 1, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, momentId: 2, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, momentId: 2, createdAt: new Date(), updatedAt: new Date() },
        { userId: 4, momentId: 2, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, momentId: 3, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, momentId: 3, createdAt: new Date(), updatedAt: new Date() },
        { userId: 4, momentId: 3, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, momentId: 4, createdAt: new Date(), updatedAt: new Date() },
        { userId: 5, momentId: 4, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, momentId: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, momentId: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 4, momentId: 5, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, momentId: 6, createdAt: new Date(), updatedAt: new Date() },
        { userId: 4, momentId: 6, createdAt: new Date(), updatedAt: new Date() },
        { userId: 5, momentId: 6, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, momentId: 7, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, momentId: 7, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, momentId: 8, createdAt: new Date(), updatedAt: new Date() },
        { userId: 4, momentId: 8, createdAt: new Date(), updatedAt: new Date() },
        { userId: 5, momentId: 8, createdAt: new Date(), updatedAt: new Date() },
        { userId: 1, momentId: 9, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, momentId: 9, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, momentId: 10, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, momentId: 10, createdAt: new Date(), updatedAt: new Date() },
        { userId: 4, momentId: 10, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, momentId: 11, createdAt: new Date(), updatedAt: new Date() },
        { userId: 5, momentId: 11, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, momentId: 12, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, momentId: 12, createdAt: new Date(), updatedAt: new Date() },
        { userId: 4, momentId: 12, createdAt: new Date(), updatedAt: new Date() },
        { userId: 5, momentId: 12, createdAt: new Date(), updatedAt: new Date() },
        { userId: 2, momentId: 13, createdAt: new Date(), updatedAt: new Date() },
        { userId: 3, momentId: 13, createdAt: new Date(), updatedAt: new Date() },
        { userId: 4, momentId: 13, createdAt: new Date(), updatedAt: new Date() },
    ]
};
